### ISSUE TITLE
Revisión del ejercicio:

### ISSUE THREAD

**Issue by memecast** [JessyDominguez/Function-convert-object-to-list#1]
¡¡Hola @JessyDominguez !! 
Resolviste de forma excelente el ejercicio. 
Las única observación que tengo es que pedí que la resolución teórica del ejercicio (es decir, **las respuestas a las preguntas sobre for in**) fueran redactadas en el **README.md** del documento/repositorio. 
Para completar este issue, te pido que por favor subas un commit con los cambios en tu README.md 

Un saludo 😄 
  -M

**Comment by JessyDominguez** [comment]
Hola @memecast !! , listo, ya realicé los cambios solicitados!!. 
Saludo!! :)

**Comment by memecast** [comment]
Excelente Jessy!! 
Cierro este Issue 😀
